name:                taurus
version:             0.1.0.0
github:              "converge-io/taurus"
license:             BSD3
author:              "Gideon Farrell"
maintainer:          "gideon@converge.io"
copyright:           "2022 Converge"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/converge-io/taurus#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- either
- errors-ext
- hasql
- hasql-th
- hspec
- hspec-megaparsec
- http-api-data
- megaparsec
- profunctors
- servant-server
- text
- transformers
- vector
- wai
- warp

library:
  source-dirs: src

executables:
  taurus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taurus

tests:
  taurus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - taurus
    - hspec
    - hspec-megaparsec
